name: Pnpm

description: Install pnpm

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
      with:
        node-version-file: .node-version
        cache: pnpm

    - name: pnpm
      shell: bash
      env:
        COREPACK_INTEGRITY_KEYS: 0
      run: |
        corepack enable
        pnpm install

    - name: yarn
      shell: bash
      env:
        COREPACK_INTEGRITY_KEYS: 0
      run: |
        cd fixtures/pnp
        corepack enable
        yarn install
