name: Pnpm

description: Install pnpm

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4

    - name: yarn
      shell: bash
      run: |
        cd fixtures/pnp
        corepack enable
        yarn install

    - uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: pnpm

    - run: pnpm install
      shell: bash
