name: Publish Crate

on:
  push:
    branches:
      - main
    paths:
      - Cargo.toml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # for softprops/action-gh-release@v1
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: ./.github/actions/rustup
        with:
          save-cache: false

      - name: Cargo check
        run: cargo check --locked

      - uses: katyo/publish-crates@v2
        id: publish
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true

      - name: Create GitHub Release
        if: steps.publish.outcome == 'success'
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ join(fromJSON(steps.publish.outputs.published).version, '') }}
          draft: true
          fail_on_unmatched_files: true
          generate_release_notes: true
