name: Release Plz

permissions: {}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.OXC_BOT_PAT }}

      - name: Run release-plz
        id: release-plz
        uses: MarcoIeni/release-plz-action@36d2dcf6a250ff9c4dfd2984e988d79ea67a4c6a # v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.OXC_BOT_PAT }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Bump package.json
        if: ${{ steps.release-plz.outputs.prs_created }}
        env:
          GH_TOKEN: ${{ secrets.OXC_BOT_PAT }}
          PR_NUMBER: ${{ fromJSON(steps.release-plz.outputs.pr).number }}
          VERSION: ${{ fromJSON(steps.release-plz.outputs.pr).releases[0].version }}
        run: |
          set -e
          if [[ -n "$PR_NUMBER" ]]; then
            jq --arg version "${VERSION}" '.version = ($VERSION)' npm/package.json > tmp
            mv tmp npm/package.json

            gh pr checkout $PR_NUMBER
            git add .
            git commit --amend --no-edit
            git push --force-with-lease
          fi
